### ISSUE TITLE
Login creating an AttributeError

### ISSUE THREAD

**Issue by Supwatch** [nolmoonen/spoorspelbaar#5]
When logging in, it opens a debug window instead of logging in.

![image](https://user-images.githubusercontent.com/16761227/37408998-8f1d7eb2-279d-11e8-8785-f44d9335e70e.png)

Environment:

Request Method: POST
Request URL: http://131.155.238.30:8000/user/login/

Django Version: 2.0.3
Python Version: 3.6.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'templates',
 'django_crontab',
 'stations',
 'advices',
 'voting',
 'user',
 'reset']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "C:\Program Files\Python36\lib\site-packages\django\core\handlers\exception.py" in inner
  35.             response = get_response(request)

File "C:\Program Files\Python36\lib\site-packages\django\core\handlers\base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "C:\Program Files\Python36\lib\site-packages\django\core\handlers\base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\Users\bram\source\repos\spoorspelbaar\djangobackend\user\views.py" in login
  117.         if form.is_valid():

File "C:\Program Files\Python36\lib\site-packages\django\forms\forms.py" in is_valid
  179.         return self.is_bound and not self.errors

File "C:\Program Files\Python36\lib\site-packages\django\forms\forms.py" in errors
  174.             self.full_clean()

File "C:\Program Files\Python36\lib\site-packages\django\forms\forms.py" in full_clean
  377.         self._clean_form()

File "C:\Program Files\Python36\lib\site-packages\django\forms\forms.py" in _clean_form
  404.             cleaned_data = self.clean()

File "C:\Users\bram\source\repos\spoorspelbaar\djangobackend\user\forms.py" in clean
  138.         pk = self.cleaned_data.get('pk').lower()

Exception Type: AttributeError at /user/login/
Exception Value: 'NoneType' object has no attribute 'lower'

**Comment by Supwatch** [comment]
Bug located inside the forms.py file, where the username is checked. This means that the username input is not generated correctly or that some of its attributes are misplaced / missing.

**Comment by nolmoonen** [comment]
Issue caused by improper use of form in template. The fields specified are deleted and different ones are added by @Supwatch. Probably caused in one of these commits:

- [More updates (1)](https://github.com/nolmoonen/spoorspelbaar/commit/e5108f5d67dbafb8e547eee1a2f185f2986beb44)
- [More updates (2)](https://github.com/nolmoonen/spoorspelbaar/commit/66d41cc104c389088d0f467b0582ba36c6382d85)
- [Removed things that are broken](https://github.com/nolmoonen/spoorspelbaar/commit/f9c63f7ea1c9ae88a8855251c25b0641e7e7d20c
)
